#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Command Line tool to query the movie rate in Douban
    douban
    ~~~~~~
    Query Movie/Book info in Douban
    :Date  09/20/2017
    :author yuanjingsong
    :license: MIT
    :copyright: Copyright (c) 2017 Yuanjingsong. All rights reserved
"""
import requests
import json
from pprint import pprint
import sys

__name__ = "douban-cli"
__version__ = "0.0.1"
__description__ = "命令行下查询豆瓣电影图书信息"
__keywords__ = "Query Movie or Book info in Douban via CLI"
__author__ = "yuanjingsong"
__constact__ = "yuanjingsongxjtu@gmail.com"
__license__ = "MIT"

class Movie():
    api = "http://api.douban.com/v2/movie/search?q="
    movie_detail_api = "http://api.douban.com/v2/movie/subject/"
    def __init__(self,argv):
        movie = ''
        if len(argv) > 0 :
            for s in argv:
                movie = movie + s + ""
            self.api = self.api + movie
        self.search()
    def search(self):
        try:
            query = requests.get(self.api).json()
            id = query['subjects'][0]['id']
            movie_detail = requests.get(self.movie_detail_api + id).json()
            print('\033[1;31m####################################################### \033[0m')
            print("影片:  " + movie_detail["title"] + "\n" )
            print("上映:  " + movie_detail['year'] + "\n")
            print("类型:  " + movie_detail["genres"][0] + movie_detail['genres'][1] + "\n")
            if(movie_detail.__contains__("duration")):
                print("片长:  " + movie_detail['duration'] + "\n")
            print("豆瓣评分:  " +str(movie_detail['rating']['average']) + "\n")
            print("简介:  " + movie_detail['summary'])
            print('\033[1;31m###################################################### \033[0m')
        except Exception as e:
            print("search wrong")
def main():
    Movie(sys.argv[1])
main()
